/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Basic project with metadata, processes, and tasks
 */
export interface ProjectInformation {
  /**
   * The unique identifier for a project
   */
  projectId?: string;
  /**
   * Type of project
   */
  projectType?: string;
  /**
   * Unique, human readable name of the project
   */
  projectName?: string;
  /**
   * Status of the project
   */
  projectStatus?: string;
  /**
   * URI of the project team template associated with this type of project
   */
  teamTemplateURI?: string;
  team?: ProjectTeam;
  /**
   * Date the project is created
   */
  created?: string;
  /**
   * Set of categorized subprocesses
   */
  processesArray?: {
    /**
     * Category for associated tasks that define a subprocess
     */
    subProcessCategory?: string;
    /**
     * Associated tasks that define a subprocess
     */
    subProcessTasks?: Task[];
  }[];
}
/**
 * project team created for this project
 */
export interface ProjectTeam {
  /**
   * List of team roles and people assigned to that role
   */
  teamRoleList?: {
    /**
     * Name of role
     */
    teamRole?: string;
    /**
     * List of people assigned to role and dates they began and ended in role
     */
    teamMembersInRole?: string[];
  }[];
}
/**
 * Basic task data
 */
export interface Task {
  /**
   * A unique identifier for a task
   */
  taskId: string;
  /**
   * Title of the task
   */
  taskTitle: string;
  /**
   * Description of the task
   */
  taskDescription?: string;
  /**
   * Reference data to support completion of the task
   */
  taskReferenceList?: {
    /**
     * Name of the reference item
     */
    referenceName?: string;
    /**
     * Description of the reference item
     */
    referenceDescription?: string;
    /**
     * Type of reference item
     */
    referenceType?: string;
    /**
     * URI to access reference item
     */
    referenceURI?: string;
  }[];
  /**
   * URI for supporting applications to help complete task. Value is defined during process tempalte creation.
   */
  taskApplicationURI?: string;
  /**
   * History of the status of the task
   */
  taskStatusHistory?: {
    /**
     * Status of the task
     */
    statusValue?: string;
    /**
     * Date status of the task was achieved
     */
    statusDate?: string;
    /**
     * Party responsible for setting status value
     */
    statusOwner?: string;
  }[];
  /**
   * Organizational roles responsible for completing this task.
   */
  taskRoles?: string[];
  /**
   * Individuals  responsible for completing this task.
   */
  taskOwners?: string[];
}
