/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Basic task data
 */
export interface Task {
  /**
   * A unique identifier for a task
   */
  taskId: string;
  /**
   * Title of the task
   */
  taskTitle: string;
  /**
   * Description of the task
   */
  taskDescription?: string;
  /**
   * Reference data to support completion of the task
   */
  taskReferenceList?: TaskReferenceObject[];
  /**
   * URI for supporting applications to help complete task. Value is defined during process tempalte creation.
   */
  taskApplicationURI?: string;
  /**
   * History of the status of the task
   */
  taskStatusHistory?: TaskStatusObject[];
  /**
   * Organizational roles responsible for completing this task.
   */
  taskRoles?: string[];
  /**
   * Individuals  responsible for completing this task.
   */
  taskOwners?: string[];
}
/**
 * Reference objects provide the name, description, type, and URI for materials that can help a user complete a task
 */
export interface TaskReferenceObject {
  /**
   * Name of the reference item
   */
  referenceName?: string;
  /**
   * Description of the reference item
   */
  referenceDescription?: string;
  /**
   * Type of reference item
   */
  referenceType?: string;
  /**
   * URI to access reference item
   */
  referenceURI?: string;
}
/**
 * Current status of the task, date status was achieved, and party responsible for status
 */
export interface TaskStatusObject {
  /**
   * Status of the task
   */
  statusValue?: string;
  /**
   * Date status of the task was achieved
   */
  statusDate?: string;
  /**
   * Party responsible for setting status value
   */
  statusOwner?: string;
}
