/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Basic team structure for a project
 */
export interface ProjectTeam {
  /**
   * A unique identifier for a team
   */
  teamId?: string;
  /**
   * Title of the team
   */
  teamTitle: string;
  /**
   * Description of the team
   */
  teamDescription?: string;
  /**
   * List of team roles and people assigned to that role
   */
  teamRoleList?: TeamRoleObject[];
}
/**
 * Team roles and people assigned to role
 */
export interface TeamRoleObject {
  /**
   * Name of role
   */
  teamRole?: string;
  /**
   * List of people assigned to role and dates they began and ended in role
   */
  teamMembersInRole?: string[];
}
